language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install -r requirements.txt
script:
  - tests/PID.py
  - tests/feedForward.py
