name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        python-version: ["2.7.18"]

    env:
      DISPLAY: ":99.0"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init --path)"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >> ~/.bashrc
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
          source ~/.bashrc
          pyenv install ${{ matrix.python-version }}
          pyenv global ${{ matrix.python-version }}

      - name: Verify Python version
        run: python --version
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Run tests
        run: |
          python tests/PID.py
          python tests/feedForward.py
